# Generated by Django 4.2.6 on 2023-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En Espera', 'En Espera'), ('Aceptada', 'Aceptada'), ('Entregada', 'Entregada')], default='En Espera', max_length=50),
        ),
    ]
